/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StencilButton {
        "appearance": string;
        "text": string;
    }
    interface StencilModal {
        "appearance": string;
        "buttons": string;
        "closeIcon": string;
        "header": string;
        "isopen": boolean;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStencilButtonElement extends Components.StencilButton, HTMLStencilElement {
    }
    var HTMLStencilButtonElement: {
        prototype: HTMLStencilButtonElement;
        new (): HTMLStencilButtonElement;
    };
    interface HTMLStencilModalElement extends Components.StencilModal, HTMLStencilElement {
    }
    var HTMLStencilModalElement: {
        prototype: HTMLStencilModalElement;
        new (): HTMLStencilModalElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "stencil-button": HTMLStencilButtonElement;
        "stencil-modal": HTMLStencilModalElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StencilButton {
        "appearance"?: string;
        "text"?: string;
    }
    interface StencilModal {
        "appearance"?: string;
        "buttons"?: string;
        "closeIcon"?: string;
        "header"?: string;
        "isopen"?: boolean;
        "onAction"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "stencil-button": StencilButton;
        "stencil-modal": StencilModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "stencil-button": LocalJSX.StencilButton & JSXBase.HTMLAttributes<HTMLStencilButtonElement>;
            "stencil-modal": LocalJSX.StencilModal & JSXBase.HTMLAttributes<HTMLStencilModalElement>;
        }
    }
}
